name: flutter_template

description: Template for developing an application in Flutter.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  ansicolor: ^2.0.2
  auto_route: ^7.8.0
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^9.5.0+1
  flutter_svg: ^2.0.7
  socket_io_client: ^2.0.3+1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hidable: ^1.0.5
  http: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1
  local_auth: ^2.1.7
  logging: ^1.2.0
  mockito: ^5.4.4
  shared_preferences: ^2.2.0

dev_dependencies:
  auto_route_generator: ^7.2.0
  flutter_native_splash: ^2.3.10
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


# Run command to generate .gr file
# 1) flutter pub run flutter_launcher_icons:main

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sh.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/sh.png"
  background_color_ios: "#000000"
  image_path_ios: "assets/images/sh.png"

# Run command to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create

flutter_native_splash:
  color: '#ffffff' 
  image: assets/images/logo.png
# background_image:src

# ConfiguraciÃ³n general de Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/cert.pem